from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from .core import json_text, resolve_path


PREFERENCE_ORDER = [
    "headless_command_or_script",
    "generated_x_tension_bridge",
    "ui_automation_last_resort",
]

HEADLESS_TERMS = {
    "adddir",
    "addimage",
    "cfg:",
    "command line",
    "dialog settings",
    "dlg:",
    "file header signature",
    "script",
    "scripting",
    "xt:",
    "xtparam",
}

XTENSION_TERMS = {
    "comment",
    "create object",
    "evidence object",
    "in-process",
    "label",
    "metadata",
    "partition",
    "report table",
    "search hit",
    "sector",
    "tag",
    "volume snapshot",
}


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _split_items(value: str) -> list[str]:
    return [line.strip() for line in value.replace(",", "\n").splitlines() if line.strip()]


def sanitize_identifier(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", value).strip("_")
    if not cleaned:
        raise ValueError("name must contain at least one safe identifier character")
    if not cleaned[0].isalpha():
        cleaned = f"Xways_{cleaned}"
    return cleaned[:80]


def plan_xways_operation(
    operation: str,
    *,
    known_headless: bool = False,
    known_xtension_api: bool = False,
    requires_in_process: bool = False,
    allow_ui_fallback: bool = False,
) -> dict:
    """Choose the preferred automation route for an X-Ways task."""

    normalized = operation.strip()
    if not normalized:
        raise ValueError("operation is required")

    lowered = normalized.lower()
    headless_matches = sorted(term for term in HEADLESS_TERMS if term in lowered)
    xtension_matches = sorted(term for term in XTENSION_TERMS if term in lowered)

    if known_headless or (headless_matches and not requires_in_process):
        route = "headless_command_or_script"
        next_steps = [
            "Search the local X-Ways manual/docs cache for command-line, script, Dlg:, Cfg:, XT:, and XTParam syntax.",
            "Build a dry-run launch command first.",
            "Execute only when local scope authorizes execution and XWAYS_MCP_ALLOW_EXECUTE=1.",
        ]
    elif known_xtension_api or requires_in_process or xtension_matches:
        route = "generated_x_tension_bridge"
        next_steps = [
            "Identify the documented or locally researched X-Tensions API symbols needed for the gap.",
            "Generate a case-local X-Tension bridge scaffold and record API provenance.",
            "Build/load the bridge only from local source, and write outputs to the approved case workspace.",
        ]
    else:
        route = "research_then_generate_x_tension"
        next_steps = [
            "Try local manual/docs search first; do not use case facts as web queries.",
            "If no headless command/script exists, research the X-Tensions API surface and generate a bridge scaffold.",
            "Use UI automation only after headless and X-Tension routes are exhausted or explicitly impractical.",
        ]

    if allow_ui_fallback:
        next_steps.append("UI automation is permitted only as a bounded last resort with sanitized status reporting.")
    else:
        next_steps.append("UI automation is not selected by default; ask for explicit approval or a documented exception.")

    return {
        "operation": normalized,
        "selected_route": route,
        "preference_order": PREFERENCE_ORDER,
        "detected_headless_terms": headless_matches,
        "detected_xtension_terms": xtension_matches,
        "known_headless": known_headless,
        "known_xtension_api": known_xtension_api,
        "requires_in_process": requires_in_process,
        "allow_ui_fallback": allow_ui_fallback,
        "case_data_policy": [
            "Do not send evidence names, keys, recovered filenames, or case paths to the internet.",
            "Keep broad evidence-derived output in local files; return counts, status, and artifact paths only.",
            "Document any undocumented API usage with local provenance and version constraints.",
        ],
        "next_steps": next_steps,
    }


def _readme(name: str, purpose: str, api_reference: str) -> str:
    return f"""# {name} X-Tension Bridge

Generated by `xways-mcp` as a local bridge scaffold.

## Purpose

{purpose or "Describe the X-Ways automation gap this bridge closes."}

## Execution Policy

1. Prefer documented X-Ways command-line, script, `.dlg`, `Cfg:`, `XT:`, and
   `XTParam:*` routes first.
2. Use this X-Tension only when the operation needs in-process X-Ways access or
   no headless command/script covers the task.
3. Keep evidence-derived output in the approved local case workspace.
4. Do not print passwords, recovery keys, evidence names, recovered filenames, or
   sensitive paths to agent prompts, terminals, issues, or pull requests.

## API Reference

{api_reference or "Record the local/official X-Tensions API reference used for this bridge."}

## Runner Checklist

- Confirm the X-Ways version and license supports the required X-Tension mode.
- Record every documented API symbol used in `API_NOTES.md`.
- Mark any undocumented symbol or reverse-engineered behavior as version-bound.
- Build from local source only.
- Run against a disposable synthetic fixture before real evidence when possible.
- Write status JSON/JSONL/CSV outputs under the case workspace.
"""


def _api_notes(documented_symbols: list[str], undocumented_symbols: list[str]) -> str:
    documented = "\n".join(f"- `{item}`" for item in documented_symbols) or "- None recorded yet."
    undocumented = "\n".join(f"- `{item}`" for item in undocumented_symbols) or "- None recorded."
    return f"""# API Notes

## Documented Symbols

{documented}

## Undocumented Or Locally Researched Symbols

{undocumented}

For undocumented behavior, record:

- X-Ways executable name and version
- where the symbol/behavior was found
- expected calling convention and argument ownership
- failure behavior
- why no documented/headless route was sufficient
"""


def _cpp_template(name: str) -> str:
    return f"""// Generated by xways-mcp.
// This is a conservative bridge scaffold, not a finished X-Tension.
// Wire this file to the locally approved X-Tensions API header before building.

#include <windows.h>

namespace {{
constexpr wchar_t kBridgeName[] = L"{name}";
}}

// TODO: Include the local X-Tensions API header and replace the placeholder
// exports below with the exact documented signatures for the target X-Ways
// version. Keep output paths case-local and pass them through XTParam values
// or a local configuration file.

extern "C" __declspec(dllexport) int __stdcall XwaysMcpBridge_Probe() {{
  return kBridgeName[0] ? 1 : 0;
}}

BOOL APIENTRY DllMain(HMODULE, DWORD, LPVOID) {{
  return TRUE;
}}
"""


def _build_script(name: str) -> str:
    return f"""$ErrorActionPreference = 'Stop'

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$Source = Join-Path $Root 'src\\{name}.cpp'
$Dist = Join-Path $Root 'dist'
$Out = Join-Path $Dist '{name}.dll'

if (-not $env:XWAYS_XTENSION_API_INCLUDE) {{
  throw 'Set XWAYS_XTENSION_API_INCLUDE to the local X-Tensions API include directory before building.'
}}

New-Item -Path $Dist -ItemType Directory -Force | Out-Null
cl /LD /EHsc /I "$env:XWAYS_XTENSION_API_INCLUDE" /Fe:$Out $Source
"""


def create_xtension_scaffold(
    name: str,
    *,
    output_root: str = "xtensions",
    purpose: str = "",
    api_reference: str = "",
    documented_symbols: str = "",
    undocumented_symbols: str = "",
    force: bool = False,
) -> dict:
    identifier = sanitize_identifier(name)
    root = resolve_path(output_root) / identifier
    if root.exists() and any(root.iterdir()) and not force:
        return {
            "created": False,
            "path": str(root),
            "reason": "scaffold already exists; pass force=true to overwrite generated files",
        }

    documented = _split_items(documented_symbols)
    undocumented = _split_items(undocumented_symbols)
    files = {
        "manifest.json": json_text(
            {
                "name": identifier,
                "purpose": purpose,
                "created_utc": _utc_now(),
                "generator": "xways-mcp",
                "execution_policy": PREFERENCE_ORDER,
                "api_reference": api_reference,
                "documented_symbols": documented,
                "undocumented_symbols": undocumented,
                "output_policy": "case-local artifacts only; no secrets or evidence-derived payloads in prompts",
            }
        )
        + "\n",
        "README.md": _readme(identifier, purpose, api_reference),
        "API_NOTES.md": _api_notes(documented, undocumented),
        f"src/{identifier}.cpp": _cpp_template(identifier),
        "build.ps1": _build_script(identifier),
    }

    written: list[str] = []
    for relative, content in files.items():
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(relative)

    return {
        "created": True,
        "name": identifier,
        "path": str(root),
        "files": written,
        "next_steps": [
            "Confirm the X-Tensions API signatures from local/official docs.",
            "Replace placeholder exports with documented callbacks.",
            "Build locally and test against disposable fixtures before evidence.",
            "Document any version-bound or undocumented behavior in API_NOTES.md.",
        ],
    }
